# Generated by Django 2.2.1 on 2019-05-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=42)),
                ('max_possible_result', models.SmallIntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('id_test_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorsapp.TestTemplates')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_pass', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=20)),
                ('surname', models.TextField(max_length=50)),
                ('class_name', models.TextField(max_length=10)),
                ('result', models.SmallIntegerField()),
                ('victim_mac_address', models.TextField(default='empty', max_length=20)),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorsapp.TestSchedule')),
            ],
        ),
    ]
