# Generated by Django 2.2.1 on 2019-06-18 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=42)),
                ('description', models.TextField()),
                ('max_possible_result', models.SmallIntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('id_test_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorsapp.TestTemplates')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_pass', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=10)),
                ('result', models.SmallIntegerField()),
                ('victim_mac_address', models.CharField(default='empty', max_length=20)),
                ('key', models.CharField(default='dsycfgcrvdxfgggfhjvjy7tgfvb3b483n23123serddsdrq78yhy', max_length=100)),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorsapp.TestSchedule')),
            ],
        ),
    ]
