# Generated by Django 2.2.1 on 2019-06-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='key',
        ),
    ]
